import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {VT323 } from 'next/font/google';
import { AuthProvider } from "../context/AuthContext";

const vt323 = VT323({weight:"400",subsets:["latin"], variable:"--font-vt323"});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * The root layout of the app, which sets up the HTML, body and font styles.
 *
 * @param {{ children: React.ReactNode }} props The props of the component.
 * @returns {React.ReactElement} The rendered component.
 */
export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`${vt323.variable} ${geistSans.variable} ${geistMono.variable} antialiased bg-red-500`}
      >
        <AuthProvider>
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}
