import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { VT323 } from "next/font/google";
import { AuthProvider } from "../context/AuthContext";
import { Toaster } from "react-hot-toast";
import NotificationsProvider from "../context/NotificacionesContext";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";

const vt323 = VT323({ weight: "400", subsets: ["latin"], variable: "--font-vt323" });
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className={`${geistSans.variable} ${geistMono.variable} ${vt323.variable}`}>
      <body>
        <AuthProvider>
          <NotificationsProvider>
            <main>{children}</main>
            <Toaster position="top-right" />
          </NotificationsProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
